# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\x12\x06search\"0\n\rSearchRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08keywords\x18\x02 \x03(\t\"-\n\x0eSearchResponse\x12\x1b\n\x13search_results_text\x18\x01 \x03(\t2H\n\rSearchService\x12\x37\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseB=Z;github.com/mehulambastha/wrink-ai/backend/gen/search;searchb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/mehulambastha/wrink-ai/backend/gen/search;search'
  _globals['_SEARCHREQUEST']._serialized_start=24
  _globals['_SEARCHREQUEST']._serialized_end=72
  _globals['_SEARCHRESPONSE']._serialized_start=74
  _globals['_SEARCHRESPONSE']._serialized_end=119
  _globals['_SEARCHSERVICE']._serialized_start=121
  _globals['_SEARCHSERVICE']._serialized_end=193
# @@protoc_insertion_point(module_scope)
