# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'llm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tllm.proto\x12\x03llm\"Z\n\x13GeneratePostRequest\x12\x14\n\x0cscraped_text\x18\x01 \x03(\t\x12\x15\n\rstyle_profile\x18\x02 \x01(\t\x12\x16\n\x0eoriginal_topic\x18\x03 \x01(\t\")\n\x14GeneratePostResponse\x12\x11\n\tpost_text\x18\x01 \x01(\t2Q\n\nLLMService\x12\x43\n\x0cGeneratePost\x12\x18.llm.GeneratePostRequest\x1a\x19.llm.GeneratePostResponseB7Z5github.com/mehulambastha/wrink-ai/backend/gen/llm;llmb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/mehulambastha/wrink-ai/backend/gen/llm;llm'
  _globals['_GENERATEPOSTREQUEST']._serialized_start=18
  _globals['_GENERATEPOSTREQUEST']._serialized_end=108
  _globals['_GENERATEPOSTRESPONSE']._serialized_start=110
  _globals['_GENERATEPOSTRESPONSE']._serialized_end=151
  _globals['_LLMSERVICE']._serialized_start=153
  _globals['_LLMSERVICE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
